name: rubber
description: Rubber is an elastic bottom sheet widget with the customizable material spring animation.
version: 1.0.1
homepage: https://github.com/mcrovero/rubber

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: 1.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
